#FROM bash:5.2.15 as bash-base
#FROM bash:alpine3.18 as bash-base
FROM ubuntu:22.04 as bash-base

# install tools


##
FROM bash-base as bash-app

#
COPY . /app
WORKDIR /app

# create catalogs
RUN mkdir -p /backup_output \
  && mkdir -p /backup_source

#
CMD chmod a+x ./.develop/run_in_docker_dev.sh && /bin/bash ./.develop/run_in_docker_dev.sh
